version: '3'

services:

  dockerhost:
    image: qoomon/docker-host
    cap_add: [ 'NET_ADMIN', 'NET_RAW' ]
    restart: on-failure

  kong-database:
    image: postgres:9.5
    environment:
      - POSTGRES_USER=kong
      - POSTGRES_DB=kong
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  kong:
    #image: kong-docker-kong-enterprise-edition-docker.bintray.io/kong-enterprise-edition:0.35-1-centos
    image: kong:1.2-centos
    #image: kong:2.0-centos
    depends_on:
      - kong-database
    environment:
      - KONG_LICENSE_DATA=${KONG_LICENSE_DATA}
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=kong-database
      - KONG_PROXY_ACCESS_LOG=/dev/stdout
      - KONG_ADMIN_ACCESS_LOG=/dev/stdout
      - KONG_PROXY_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_LISTEN=0.0.0.0:8001
      - KONG_ADMIN_LISTEN_SSL=0.0.0.0:8444
      - KONG_VITALS=off
      - KONG_PORTAL=off
      - KONG_LOG_LEVEL=debug
      - KONG_PLUGINS=bundled,${NAME}
    volumes:
      - plugin-development:/plugin-development
    command:
      - /bin/bash
      - -c
      - |
        sleep 5
        mkdir -p /usr/local/lib/luarocks/rocks/${NAME}/${VERSION}/
        ln -s /plugin-development/${NAME}-${VERSION}.rockspec /usr/local/lib/luarocks/rocks/${NAME}/${VERSION}/${NAME}-${VERSION}.rockspec
        ln -s /plugin-development/src /usr/local/share/lua/5.1/kong/plugins/${NAME}
        sed -i "/proxy_set_header.*X-Forwarded-For/d; /proxy_set_header.*X-Real-IP/d;" /usr/local/share/lua/5.1/kong/templates/nginx_kong.lua
        kong migrations bootstrap
        /usr/local/bin/kong start --run-migrations --vv
    ports:
      - "8000:8000"
      - "8443:8443"
      - "8001:8001"
      - "8444:8444"
      - "8002:8002"
      - "8445:8445"
      - "8003:8003"
      - "8004:8004"

volumes:

  plugin-development:
    driver: local
    driver_opts:
       type: none
       o: bind
       device: ${PWD}/
